apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: Ym9va3MtZGIuY2g4c3N5eXFhZjJnLmFwLXNvdXRoLTEucmRzLmFtYXpvbmF3cy5jb20=
  db_username: YWRtaW4=
  db_password: c3JpdmFyZGhhbg==

